#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := ESP32Board

EXTRA_COMPONENT_DIRS := $(realpath ../..)

include $(IDF_PATH)/make/project.mk

EXTRA_COMPONENT_DIRS := $(realpath /Users/spartan117/projects/project-pheonix/esp-aws-iot/)
